# Generated by Django 5.2.11 on 2026-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_profile_about_long_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('award', 'Award / Penghargaan'), ('competition', 'Kompetisi'), ('certification', 'Sertifikasi'), ('project', 'Project Highlight'), ('other', 'Lainnya')], default='other', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('highlight', models.CharField(blank=True, help_text='Angka/hasil singkat, mis: "Top 1%", "Gold Medal", "Winner".', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Tampilkan sebagai highlight di halaman utama.')),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', '-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('credential_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Tampilkan di highlight sertifikat.')),
            ],
            options={
                'ordering': ['ordering', '-issue_date', 'name'],
            },
        ),
    ]
