# Generated by Django 5.2.11 on 2026-02-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_achievement_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(help_text='Contoh: SMA IPA, Sarjana Komputer', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Kosongkan jika masih berlangsung.', null=True)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['ordering', '-start_date'],
            },
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_url',
            new_name='instagram_url',
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF atau dokumen terkait project.', null=True, upload_to='documents/'),
        ),
    ]
