# Generated by Django 5.2.11 on 2026-02-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education_rename_twitter_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, help_text='Upload sertifikat (PDF/JPG/PNG).', null=True, upload_to='certificates/files/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy field. Gunakan "file" untuk upload baru.', null=True, upload_to='certificates/'),
        ),
    ]
