# Generated by Django 5.2.11 on 2026-09-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_certificate_file_alter_project_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='Contoh: Sarjana Komputer, S1 Teknik Informatika', max_length=200),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Contoh: Research Assistant, Data Center Intern', max_length=200)),
                ('organization', models.CharField(help_text='Contoh: LPPM UPI YPTK Padang, Dinas Komunikasi dan Informatika', max_length=200)),
                ('employment_type', models.CharField(choices=[('Research & Academic', 'Research & Academic'), ('Industrial Internship', 'Industrial Internship'), ('Apprenticeship', 'Apprenticeship / Virtual Intern'), ('Organizational Leadership', 'Organizational Leadership'), ('Talent Acceleration', 'Talent Acceleration'), ('Bootcamp & Training', 'Bootcamp & Training'), ('Other', 'Other')], default='Industrial Internship', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Contoh: Padang, Sumatera Barat', max_length=150)),
                ('location_type', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-site', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Kosongkan jika masih aktif / berlangsung.', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Centang jika ini adalah posisi aktif Anda saat ini.')),
                ('description', models.TextField(help_text='Deskripsi ruang lingkup pekerjaan dan tanggung jawab.')),
                ('highlights', models.TextField(blank=True, help_text='Poin-poin pencapaian atau metrik terukur. Pisahkan setiap poin dengan baris baru.')),
                ('technologies_summary', models.CharField(blank=True, help_text='Ringkasan tech stack (misal: "Python, Docker, Kafka, YOLOv8")', max_length=255)),
                ('link', models.URLField(blank=True, help_text='Tautan proyek, dokumen pendukung, atau sertifikat terkait.')),
                ('is_featured', models.BooleanField(default=True, help_text='Tampilkan di sorotan utama portfolio.')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.skill')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['ordering', '-start_date', 'title'],
            },
        ),
    ]
